# -*- coding: utf-8 -*-
{
	"name" : "Reporte de Caja version Appex",
	"version" : "17.0.0.0",
	"category" : "Point of Sale",
	"depends" : ['base','sale','point_of_sale'],
	"author": "AppexBolivia",
	'summary': 'Reporte de Caja solo metodos de pago y montos',
	"description": """
		
	""",
	"website" : 'https://www.appexbo.com/',
	"data": [
		'security/ir.model.access.csv',
		'views/pos_reports.xml',
		'views/product_view.xml',

		#adiciones erick
		'wizard/audit_report_view.xml',
		'reports/AuditReport.xml',
		
		#'wizard/pos_sale_summary.xml',
		#'wizard/sales_summary_report.xml',
		#'wizard/x_report_view.xml',
		#'wizard/z_report_view.xml',
		#'wizard/top_selling.xml',
		#'wizard/top_selling_report.xml',
		#'wizard/profit_loss_report.xml',
		#'wizard/pos_payment_report.xml',
		#'wizard/profit_loss.xml',
		#'wizard/pos_payment.xml',
	],
	'assets': {
		'point_of_sale._assets_pos': [
			'reporte_cierre_de_caja/static/src/css/reports.css',
			'reporte_cierre_de_caja/static/src/js/models.js',
			'reporte_cierre_de_caja/static/src/js/AuditReport/ReportLocationButtonWidget.js',
			'reporte_cierre_de_caja/static/src/js/AuditReport/PopupLocationWidget.js',
			'reporte_cierre_de_caja/static/src/js/AuditReport/LocationReceiptScreen.js',
			'reporte_cierre_de_caja/static/src/js/AuditReport/LocationReceipt.js',
			'reporte_cierre_de_caja/static/src/js/CategorySummary/ReportCategoryButtonWidget.js',
			'reporte_cierre_de_caja/static/src/js/CategorySummary/PopupCategoryWidget.js',
			'reporte_cierre_de_caja/static/src/js/CategorySummary/CategoryReceiptWidget.js',
			'reporte_cierre_de_caja/static/src/js/CategorySummary/XMLPosCategorySummaryReceipt.js',
			'reporte_cierre_de_caja/static/src/js/OrderSummary/ReportOrderButtonWidget.js',
			'reporte_cierre_de_caja/static/src/js/OrderSummary/PopupOrderWidget.js',
			'reporte_cierre_de_caja/static/src/js/OrderSummary/OrderReceiptWidget.js',
			'reporte_cierre_de_caja/static/src/js/OrderSummary/XMLPosOrderSummaryReceipt.js',
			'reporte_cierre_de_caja/static/src/js/PaymentReport/ReportPaymentButtonWidget.js',
			'reporte_cierre_de_caja/static/src/js/PaymentReport/PaymentSummaryPopup.js',
			'reporte_cierre_de_caja/static/src/js/PaymentReport/PaymentReceiptWidget.js',
			'reporte_cierre_de_caja/static/src/js/PaymentReport/XMLPosPaymentSummaryReceipt.js',
			'reporte_cierre_de_caja/static/src/js/ReportProductButton/ReportProductButtonWidget.js',
			'reporte_cierre_de_caja/static/src/js/ReportProductButton/PopupProductWidget.js',
			'reporte_cierre_de_caja/static/src/js/ReportProductButton/ProductReceiptWidget.js',
			'reporte_cierre_de_caja/static/src/js/ReportProductButton/XMLPosProductSummaryReceipt.js',
			'reporte_cierre_de_caja/static/src/xml/AuditReport.xml',
			'reporte_cierre_de_caja/static/src/xml/CategoryReport.xml',
			'reporte_cierre_de_caja/static/src/xml/OrderReport.xml',
			'reporte_cierre_de_caja/static/src/xml/PaymentReport.xml',
			'reporte_cierre_de_caja/static/src/xml/ProductReport.xml',
		],
	},
	"auto_install": False,
	"installable": True,
	"images":['static/description/Banner.gif'],
	'license': 'LGPL-3',
}